image: ruby

variables:
  JEKYLL_ENV: production
  LC_ALL: C.UTF-8

stages:
  - deploy
  - build

before_script:
  #- apt-get update
  #- apt-get install exempi python3 python3-pip imagemagick libmagickwand-dev libatlas-base-dev liblapack-dev libblas-dev gfortran -y
  #- pip3 install python-xmp-toolkit numpy svgwrite svgpathtools requests rdflib rdflib-jsonld pillow

#imageclassification:
#  stage: build
#  script:
#  - mkdir classification
#  - mkdir classification/line
#  - mkdir classification/char
#  - mkdir classification/charline
#  - mkdir classification/word
#  - mkdir classification/wordline
#  - mkdir classification/charannotations
#  - mkdir classification/wordannotations
#  - mkdir classification/lineannotations
#  - mkdir classification/3dannotations
#  - mkdir classification/char_annotated
#  - mkdir classification/normalized_signs_comp
#  - mkdir classification/normalized_signs_na
#  - mkdir classification/normalized_signs_ob
#  - cp result/* classification/charannotations/
  #- cp result3d/* classification/3dannotations/
#  - python3 createThumbnails.py classification true 
  #- python3 prepare_zooniverse.py 2 250
  #- python3 createThumbnails.py classification/line/ true Line
#  artifacts:
#    paths:
#    - classification
#  except:
#  - master 
#  - master-local

pages:
  stage: deploy
  script:
  - bundle install
  - bundle exec jekyll build -d public
  #- python3 extractPaleoCodes.py
  artifacts:
    paths:
    - public
  only:
  - master-local
