image: ruby:2.5

variables:
  JEKYLL_ENV: production
  LC_ALL: C.UTF-8

before_script:
  - bundle install
  - apt-get update
  - apt-get install python3 python3-pip imagemagick libmagickwand-dev -y
  - pip3 install wand numpy svgwrite svgpathtools requests

imageclassification:
  stage: build
  script:
  - mkdir classification
  - mkdir classification/line
  - mkdir classification/char
  - python3 createThumbnails.py classification true Transliteration
  #- python3 createThumbnails.py classification/line/ true Line
  artifacts:
    paths:
    - classification
  only:
  - master

pages:
  stage: deploy
  script:
  - bundle exec jekyll build -d public
  - python3 extractPaleoCodes.py
  artifacts:
    paths:
    - public
  only:
  - master
