image: ruby

variables:
  JEKYLL_ENV: production
  LC_ALL: C.UTF-8

before_script:
  - gem install bundler:1.13.6
  - bundle install
  - apt-get update
  - apt-get install exempi python3 python3-pip imagemagick libmagickwand-dev -y
  - pip3 install python-xmp-toolkit numpy svgwrite svgpathtools requests rdflib rdflib-jsonld pillow

imageclassification:
  stage: build
  script:
  - mkdir classification
  - mkdir classification/line
  - mkdir classification/char
  - mkdir classification/word
  - mkdir classification/charannotations
  - mkdir classification/wordannotations
  - mkdir classification/lineannotations
  - mkdir classification/3dannotations
  - mkdir classification/char_annotated
  - mkdir classification/normalized_signs_comp
  - mkdir classification/normalized_signs_na
  - mkdir classification/normalized_signs_ob
  - cp result/* classification/charannotations/
  #- cp result3d/* classification/3dannotations/
  - python3 createThumbnails.py classification true 
  #- python3 createThumbnails.py classification/line/ true Line
  artifacts:
    paths:
    - classification
  only:
  - master

pages:
  stage: deploy
  script:
  - bundle exec jekyll build -d public
  - python3 extractPaleoCodes.py
  artifacts:
    paths:
    - public
  only:
  - master
